version: '3.4'

networks:
  dev:
    driver: bridge

services:
  postgres:
    container_name: postgres_container
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /data/postgres
      POSTGRES_DB: medicalFiles
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
        - dev
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@cholecystitis.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    networks:
        - dev

  webapi:
    container_name: webapi
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
    ports:
      - "5000:80"
    networks:
        - dev
        
  client:
    container_name: client
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ./webclient
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
        - dev
  proxy:
    image: nginx:mainline
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
        - dev

volumes:
    postgres:
    pgadmin: